# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 384)
        Dialog.setStyleSheet("")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(8, 7, 400, 370))
        self.widget_2.setStyleSheet("background-color: #e9e7ef")
        self.widget_2.setObjectName("widget_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 60))
        self.widget.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 15, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.picLabel = QtWidgets.QLabel(self.widget_2)
        self.picLabel.setGeometry(QtCore.QRect(60, 150, 120, 120))
        self.picLabel.setText("")
        self.picLabel.setObjectName("picLabel")
        self.acceptButton = QtWidgets.QPushButton(self.widget_2)
        self.acceptButton.setGeometry(QtCore.QRect(80, 315, 80, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.acceptButton.setFont(font)
        self.acceptButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acceptButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.acceptButton.setStyleSheet("QPushButton{background-color:rgb(228, 198, 208);;border:0px;border-radius:5px;}\n"
"\n"
"QPushButton:hover{color: rgb(249, 144, 111);}")
        self.acceptButton.setFlat(True)
        self.acceptButton.setObjectName("acceptButton")
        self.nameLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.nameLineEdit.setGeometry(QtCore.QRect(50, 90, 300, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setKerning(True)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nameLineEdit.setMaxLength(20)
        self.nameLineEdit.setFrame(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.rejectButton = QtWidgets.QPushButton(self.widget_2)
        self.rejectButton.setGeometry(QtCore.QRect(240, 315, 80, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.rejectButton.setFont(font)
        self.rejectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rejectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rejectButton.setStyleSheet("QPushButton:hover{color: rgb(249, 144, 111);}\n"
"QPushButton{border:1px;\n"
"border-radius:5px;background-color:white}")
        self.rejectButton.setObjectName("rejectButton")
        self.fileDialogButton = QtWidgets.QPushButton(self.widget_2)
        self.fileDialogButton.setGeometry(QtCore.QRect(220, 240, 80, 25))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.fileDialogButton.setFont(font)
        self.fileDialogButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileDialogButton.setStyleSheet("QPushButton{border:0px;\n"
"border-radius:4px;}\n"
"QPushButton:hover{color: rgb(249, 144, 111);}")
        self.fileDialogButton.setObjectName("fileDialogButton")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(0, 300, 400, 3))
        self.line.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(55, 275, 130, 3))
        self.line_2.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.line_2.setLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setGeometry(QtCore.QRect(55, 142, 130, 3))
        self.line_3.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.line_3.setLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setGeometry(QtCore.QRect(55, 143, 3, 134))
        self.line_4.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.line_4.setLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.widget_2)
        self.line_5.setGeometry(QtCore.QRect(185, 143, 3, 134))
        self.line_5.setStyleSheet("background-color: rgb(228, 198, 208);")
        self.line_5.setLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(6, 0, 404, 7))
        self.label.setStyleSheet("border-image: url(:/shade/tm.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(6, 375, 402, 7))
        self.label_3.setStyleSheet("border-image: url(:/shade/bm.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(2, 5, 7, 372))
        self.label_4.setStyleSheet("border-image: url(:/shade/lm.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(405, 5, 7, 372))
        self.label_5.setStyleSheet("border-image: url(:/shade/rm.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_4.raise_()
        self.label_3.raise_()
        self.widget_2.raise_()
        self.label.raise_()
        self.label_5.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "新建歌单"))
        self.acceptButton.setText(_translate("Dialog", "创建"))
        self.acceptButton.setShortcut(_translate("Dialog", "Return"))
        self.nameLineEdit.setPlaceholderText(_translate("Dialog", " 请输入新的歌单标题"))
        self.rejectButton.setText(_translate("Dialog", "取消"))
        self.rejectButton.setShortcut(_translate("Dialog", "Esc"))
        self.fileDialogButton.setText(_translate("Dialog", "选择头像"))

import static.bgsrc_rc
